name: DevOps

on:
  push:

jobs:
  ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update Image
        uses: ./action/
        with:
          suite: updateimage

      - name: Some other actions in between
        run: echo "Some other steps here..."

      - name: Keepsandbox and Deliverability
        uses: ./action/
        with:
          suite: "keepsandbox, deliverability"
